config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  constraints ValidSortOrder do

    devise_for :users
    resources :users do
      member do
        get 'posts(/:sortby)' => 'posts#user_posts', :as => :user_posts
        get 'favourites(/:sortby)' => 'posts#user_favourites', :as => :user_favourites
        get :admin_edit
        patch :admin_update
      end
    end

    resources :categories, :path => 'slackegory', param: :slug, :except => :show do
      member do
        get 'subscribe' => 'categories#subscribe'
        get 'unsubscribe' => 'categories#unsubscribe'
      end
    end
    get 'slackegory/:slug(/:sortby)' => 'posts#category', as: :category_posts



    get 'subscriptions/(:sortby)' => 'posts#subscriptions', :as => :subscriptions_posts
    
    resources :posts, :path => '/' do
      member do
        get 'upvote' => 'posts#upvote'
        get 'downvote' => 'posts#downvote'

        get 'favour' => 'posts#favour'
        get 'unfavour' => 'posts#unfavour'

        # DELETE is actually not very cruddy/resty for marking it as such, but makes it look like an actuall delete
        delete 'delete' => 'posts#mark_as_deleted'
      end
      collection do
        get '(:sortby)' => 'posts#index', :as => :sorted
      end
      resources :comments
    end
  end # ValidSortOrderConstraint

  authenticate :user, lambda { |u| u.admin? } do
    scope "/admin" do
      get 'posts/deleted' => 'posts#index_deleted', :as => :index_deleted
    end
  end






end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :posts
  has_many :categories
  has_many :votes
  has_many :comments

  has_many :category_subscriptions
  has_many :subscriptions, through: :category_subscriptions, :source => :category
  has_many :post_favourites
  has_many :favourites, through: :post_favourites, :source => :post

  as_enum :role, user: 1, mod: 2, admin: 3

  def karma
    karma_cache
  end

  def compute_karma
    karma = 0
    self.posts.each do |post|
      karma += post.score
    end
    self.karma_cache = karma
    self.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :admin_edit, :admin_update]

  def show
    @posts = @user.posts.last(5).reverse
    @favoured_posts = @user.favourites.last(5).reverse
  end

  def index
    @users = User.all
  end

  def edit
    authorize! :update, @user
  end


  def update
    authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # A user can edit himself, therefore make own actions and rotes for the admin actions
  # instead of making an own route for each action (promote, confirm...) put them in one admin action
  def admin_edit
    authorize! :admin_update, @user
  end

  def admin_update
    authorize! :admin_update, @user
    respond_to do |format|
      if @user.update(admin_user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    authorize! :update, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end

  def admin_user_params
    params.require(:user).permit(:approved, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_form.html.erb
<% if current_user.admin? %>
    <%= form_for @user, url: admin_update_user_path(@user), method: :patch do |f| %>
            <div class="field">
                <%= f.label "Approved" %>
                <%= f.check_box :approved %>
            </div>
            <div class="field">
                <%= f.label "Role" %>
                <%= f.select :role, enum_option_pairs(User, :role) %>
            </div>
        <br>
        <div class="actions">
            <%= f.submit 'Update' %>
        </div>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div><%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %></div>
<br>
    <div class="actions">
        <%= f.submit 'Update' %>
    </div>
<% end %>

app/views/users/admin_edit.html.erb
<h2>Edit <%= @user.name %></h2>

<%= render 'admin_form' %>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %></h2>

<%= render 'form' %>

app/views/users/index.html.erb
<table>
    <thead>
        <tr>
            <th><!-- Avatar --></th>
            <th>Name</th>
            <th>Karma</th>
            <th># Posts</th>
            <th># Comments</th>
            <th># Categories </th>
            <% if can? :manage, User %>
                <th>ID</th>
                <th>Sign in Count</th>
                <th colspan="4">Aktionen</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% User.all.each do |user|  %>
            <tr>
                <td><!-- Hier kommt mal der avatar hin --></td>
                <td><%= link_to user.name, user %></td>
                <td><%= user.karma %></td>
                <td><%= user.posts.size %></td>
                <td><%= user.comments.size %></td>
                <td><%= user.categories.size %></td>
                <% if can? :manage, User %>
                    <td><%= user.id %></td>
                    <td><%= user.sign_in_count %></td>
                    <td><%= link_to 'Anzeigen', user %></td>
                    <td><%= link_to 'Profil Bearbeiten', edit_user_path(user) %></td>
                    <td><%= link_to 'Rechte verwalten', admin_edit_user_path(user) %></td>
                    <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Sind Sie ganz und vollständig sicher?' } %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>


<% if can? :update, User  %>
    <%= link_to 'Edit User', edit_user_path(@user) %>
<% end %>

<h2>Last Posts</h2>

<div class="posts">
    <%= render partial: "posts/post", collection: @posts %>
</div>

<%= link_to 'Show More', user_posts_user_path(@user)%>


<h2>Favourites</h2>

<div class="posts">
    <%= render partial: "posts/post", collection: @favoured_posts %>
</div>

<%= link_to 'Show More', user_favourites_user_path(@user)%>