config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  constraints ValidSortOrder do

    devise_for :users
    resources :users do
      member do
        get 'posts(/:sortby)' => 'posts#user_posts', :as => :user_posts
        get 'favourites(/:sortby)' => 'posts#user_favourites', :as => :user_favourites
        get :admin_edit
        patch :admin_update
      end
    end

    resources :categories, :path => 'slackegory', param: :slug, :except => :show do
      member do
        get 'subscribe' => 'categories#subscribe'
        get 'unsubscribe' => 'categories#unsubscribe'
      end
    end
    get 'slackegory/:slug(/:sortby)' => 'posts#category', as: :category_posts



    get 'subscriptions/(:sortby)' => 'posts#subscriptions', :as => :subscriptions_posts
    
    resources :posts, :path => '/' do
      member do
        get 'upvote' => 'posts#upvote'
        get 'downvote' => 'posts#downvote'

        get 'favour' => 'posts#favour'
        get 'unfavour' => 'posts#unfavour'

        # DELETE is actually not very cruddy/resty for marking it as such, but makes it look like an actuall delete
        delete 'delete' => 'posts#mark_as_deleted'
      end
      collection do
        get '(:sortby)' => 'posts#index', :as => :sorted
      end
      resources :comments
    end
  end # ValidSortOrderConstraint

  authenticate :user, lambda { |u| u.admin? } do
    scope "/admin" do
      get 'posts/deleted' => 'posts#index_deleted', :as => :index_deleted
    end
  end






end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { where(status_cd: 1) }

  belongs_to :user
  has_and_belongs_to_many :categories

  validates :title, presence: true

  validates :url, presence: true
  validate :is_valid_url
  validates_uniqueness_of :url
  validates :categories, presence: true

  has_many :votes
  has_many :comments

  has_many :post_favourites
  has_many :favourers, through: :post_favourites, :source => :user

  after_create :compute_heat

  as_enum :status, pending: 0, published: 1, deleted: 2

  searchable_attributes :title, :description

  # sorting stuff
  VALID_SORT_ORDERS = %w(best newest hot)

  scope :best, -> { order(vote_cache: :desc)}
  scope :newest, -> { order(created_at: :desc)}
  scope :hot, -> { order(heat: :desc)}

  # a very good thing to get from global settings
  self.per_page = 20

  # ============================
  # Class Methods
  # ============================

  def self.in_user_subscriptions(user)
    sub_ids = user.subscriptions.ids
    self.joins(:posts_categories).where('category_id IN (?)', sub_ids).references(:categories).uniq
  end

  # ============================
  # Instance Methods
  # ============================

  def vote(user, amount)
    vo = self.votes.find_or_initialize_by(user: user)
    vo.amount = amount
    vo.save
    self.compute_score
    self.compute_heat
    self.user.compute_karma
  end

  def score
    self.vote_cache
  end

  def compute_score
    score = 0
    self.votes.each do |vote|
      score += vote.amount
    end

    self.vote_cache = score
    self.save
  end

  def compute_heat
    timestamp = self.created_at.to_i
    factor = 8.hours.to_i

    # simple algo for now
    self.heat = timestamp + ( self.score * factor )
    self.save
  end

  def favoured(user)
    return self.favourers.include? user
  end

  def favour(user)
    if not favoured(user)
      self.favourers << user
      self.save
      return true
    end
    return false
  end

  def unfavour(user)
    if favoured(user)
      self.favourers.delete(user)
      self.save
      return true
    end
    return false
  end

  def is_valid_url
    uri = self.url
    require 'uri'
    uri = URI.parse(url)
    if not  uri.is_a?(URI::HTTP) && !uri.host.nil?
      errors.add(:url, "must be a valid Url - Sherlock")
    end
  rescue URI::InvalidURIError
    errors.add(:url, "must be a valid Url - Sherlock")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :favour, :unfavour, :mark_as_deleted]
  before_action :load_categories
  before_action :set_user, only: [:user_posts, :user_favourites]
  before_filter :authenticate_user!, :except => [:show, :index, :user_posts]

  # GET /posts
  # GET /posts.json
  def index
    if request.params[:search]
      @posts = paginate(sort(Post.search(request.params[:search])))
    else
      @posts = paginate(sort(Post.all))
    end
  end

  def index_deleted
    authorize! :manage, Post
    # magic number 2 stands for deleted
    @posts = paginate(sort(Post.unscoped.where(status_cd: 2)))
  end


  # Probably deprecated. /categories/:id/posts user for now
  def category
    @category = Category.find_by_slug!(params[:slug])
    @posts = paginate(sort(@category.posts))
    render 'index'
  end

  def subscriptions
    # According to this so-post, this variant is way quicker
    # https://stackoverflow.com/questions/3941945/array-include-any-value-from-another-array
    # @posts = paginate(sort(Post.select{|p| p.categories.any? {|c| current_user.subscriptions.include? c }}))
    # @posts = paginate(sort(Post.all))
    # @posts = Post.all.select{|p| current_user.subscriptions.include? p.category}
    @posts = paginate(sort(Post.in_user_subscriptions(current_user)))
    render 'index'
  end

  # all posts of a specific user
  def user_posts
    @posts = paginate(sort(@user.posts))
  end

  def user_favourites
    @posts = paginate(sort(@user.favourites))
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    # if this comes from within a category, directly preselect that
    if request.params[:slackegory]
      begin
        @category = Category.find(request.params[:slackegory].to_i)
        # integer conversion returns 0 if the string does not make sense, so no need to catch anything for that
      rescue ActiveRecord::RecordNotFound => e
        # nothing has to be done here, @category just stays empty
        # probable a funny internet kid trying to exploit our roues
      end
    end
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize! :update, @post
  end

  def favour
    if not @post.favoured(current_user)
      if @post.favour(current_user)
        redirect_to @post, notice: 'Successfully favoured.'
      else
        redirect_to @post, notice: 'Could not favour.'
      end
    else
      redirect_to @post, notice: 'Could not favour.'
    end
  end

  def unfavour
    if @post.favoured(current_user)
      if @post.unfavour(current_user)
        redirect_to @post, notice: 'Successfully unfavoured.'
      else
        redirect_to @post, notice: 'Could not unfavour.'
      end
    else
      redirect_to @post, notice: 'Could not unfavour.'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize! :update, @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def mark_as_deleted
    # if a user "deletes" a post, it is only marked like this, so that admins have an overview over deleted posts
    authorize! :update, @post
    @post.status = :deleted
    if @post.save
      flash[:notice] = 'Post was successfully deleted.'
      redirect_to current_user
    else
      flash[:alert] = 'Something went wrong :/'
      redirect_to @post
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    # only admins can actually delete. This is not present in the ui yet.
    # other users will only be able to mark them as deleted
    authorize! :manage, @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post.vote(current_user, 1)
    redirect_to(:back)
  end

  def downvote
    @post.vote(current_user, -1)
    redirect_to(:back)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_user
      @user = User.find(params[:id])
    end

    def load_categories
      @categories = Category.all
    end

    def sort(posts)
      case params[:sortby]
        when 'hot' then posts.hot
        when 'best' then posts.best
        when 'newest' then posts.newest
        else posts.newest
      end
    end

    def paginate(posts)
      posts.page(params[:page] ? params[:page] : 1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :description, :status, :category_ids => [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

    <label for="">Slackegories</label>
      <% if not @category %>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
      <% else %>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, checked: @category.id) %>
      <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
	<div class="post-top">
		<span class="post-top">
      <a class="post-link" href="<%= post.url %>" target="_blank"><%= post.title %></a>
		(
      <span title="<%= post.heat %>"><%= post.score %></span>
      <span class="post-upvote-link"> <%= link_to('+', upvote_post_path(post)) %></span> /
      <span class="post-downvote-link"> <%= link_to('-', downvote_post_path(post)) %></span>
      )

      <% post.categories.each do |c| %>
      <span class="category-label">
        <%= link_to(c.name, c) %>
      </span>
      <% end %>

		</span>

    <span class="post-meta">

      <span class="post-user"><%= link_to(post.user.name, post.user) %></span>
      <%= time_ago_in_words(post.created_at) %>.

			<%= link_to post, { :class => "post-comments-link" }  do %>
        Comments
        <% if post.comments.count > 0 %>(<%= post.comments.count %>)<% end %>
      <% end  %>

	  </span>



	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= if @category
    content_for :title, @category.name
     render 'categories/category_header'
end  %>


<ul class="nav sort">
  <li class="nav-item">
    <%= link_to("Newest", :sortby => 'newest') %>
  </li>
  <li class="nav-item">
    <%= link_to("Hot", :sortby => 'hot') %>
  </li>
  <li class="nav-item">
    <%= link_to("Best Ever", :sortby => 'best') %>
  </li>
  <li class="nav-item">
    <%= link_to "Subscribed", subscriptions_posts_path %>
  </li>
</ul>

<ul class="nav categories">
  <% @categories.each do |c| %>
      <li class="nav-item">
        <%= link_to c.name, c %>
      </li>
  <% end %>
  <li class="nav-item">
    (<%= link_to("View all", categories_path) %>)
  </li>
</ul>

<div class="posts">
  <%= render partial: "post", collection: @posts %></div>
<br>

<div class="pagination-container">
  <%= will_paginate @posts %>
</div>


<% if not @category %>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
<% else %>
  <%= link_to 'New Post', new_post_path(:slackegory => @category.id), class: 'btn btn-primary' %>
<% end %>

app/views/posts/index_deleted.html.erb
<h1>Deleted Posts</h1>

<div class="pagination-container">
  <%= will_paginate @posts %>
</div>

<div class="posts">
  <%= render partial: "post", collection: @posts %></div>
<br>

app/views/posts/new.html.erb
<h1>New Post <% if @category %>
    for <%= @category.name %><% end %>
</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if @post
     content_for :title, @post.title
   end  %>

<h1><%= @post.title %> (
    <% if @post.favoured(current_user) %>
        <%= link_to('Delete from favourites', unfavour_post_path(@post)) %>
    <% else %>
        <%= link_to('Save as favourite', favour_post_path(@post)) %>
    <% end %>
)</h1>




<p>
  <%= link_to @post.url, @post.url %> 
</p>
<p>
  <%= @post.description %> 
</p>

<p>
  <strong>User:</strong>
  <%= link_to @post.user.name, @post.user %>
</p>


<ul class="nav">
  <li class="nav-item">
    Slackegories: 
  </li>
  <% @post.categories.each do |category| %>
      <li class="nav-item">
        <%= link_to category.name, category %>
      </li>
  <% end %>
</ul>


<% if can? :update, @post %>
  <%= link_to 'Edit', edit_post_path(@post) %> <br>
  <%= link_to 'Delete', delete_post_path(@post), method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
<% end %>

<h2>Comments</h2>
<h3>Add new comment</h3>
<%= render "comments/form" %>
<br>

<% @post.comments.order(created_at: :desc).each do |c| %>
  <div class="comment">
    <strong><%= c.user.name %>:</strong>
    <%= c.text %> 

    <% if can? :destroy, c %>
      <%= link_to [@post, c], method: :delete, data: { confirm: 'Are you sure?' }, class: "" do %>
        <i style="color:red" class="">x</i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/posts/user_favourites.html.erb
<h2>All Favourites of <%= @user.name %></h2>

<div class="pagination-container">
  <%= will_paginate @posts %>
</div>

<div class="posts">
    <%= render partial: "posts/post", collection: @posts %>
</div>

app/views/posts/user_posts.html.erb
<h2>All Posts of <%= @user.name %></h2>

<div class="pagination-container">
  <%= will_paginate @posts %>
</div>

<div class="posts">
    <%= render partial: "posts/post", collection: @posts %>
</div>