config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  constraints ValidSortOrder do

    devise_for :users
    resources :users do
      member do
        get 'posts(/:sortby)' => 'posts#user_posts', :as => :user_posts
        get 'favourites(/:sortby)' => 'posts#user_favourites', :as => :user_favourites
        get :admin_edit
        patch :admin_update
      end
    end

    resources :categories, :path => 'slackegory', param: :slug, :except => :show do
      member do
        get 'subscribe' => 'categories#subscribe'
        get 'unsubscribe' => 'categories#unsubscribe'
      end
    end
    get 'slackegory/:slug(/:sortby)' => 'posts#category', as: :category_posts



    get 'subscriptions/(:sortby)' => 'posts#subscriptions', :as => :subscriptions_posts
    
    resources :posts, :path => '/' do
      member do
        get 'upvote' => 'posts#upvote'
        get 'downvote' => 'posts#downvote'

        get 'favour' => 'posts#favour'
        get 'unfavour' => 'posts#unfavour'

        # DELETE is actually not very cruddy/resty for marking it as such, but makes it look like an actuall delete
        delete 'delete' => 'posts#mark_as_deleted'
      end
      collection do
        get '(:sortby)' => 'posts#index', :as => :sorted
      end
      resources :comments
    end
  end # ValidSortOrderConstraint

  authenticate :user, lambda { |u| u.admin? } do
    scope "/admin" do
      get 'posts/deleted' => 'posts#index_deleted', :as => :index_deleted
    end
  end






end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
  belongs_to :user

  has_many :category_subscriptions
  has_many :subscribers, through: :category_subscriptions, :source => :user

  has_many :sub_categories, class_name: "Category", foreign_key: "parent_category_id"
  belongs_to :parent_category, class_name: "Category"

  validates_uniqueness_of :slug
  validates_uniqueness_of :name
  validates :slug, presence: true
  validates :name, presence: true

  searchable_attributes :name, :desc

  # size of page in frontend (has nothing to do with db pagination)
  self.per_page = 20

  def subscribed(user)
    return self.subscribers.include? user
  end

  def subscribe(user)
    if not subscribed(user)
      self.subscribers << user
      self.save
      return true
    end
    return false
  end

  def unsubscribe(user)
    if subscribed(user)
      self.subscribers.delete(user)
      self.save
      return true
    end
    return false
  end

  # returns own sub_categories and their's (recursively)
  def all_sub_categories
    # watch out, self is not included in here
    self.sub_categories.map do |category|
      [category] + category.all_sub_categories
    end.flatten
  end

  def all_posts
    category_ids = self.all_sub_categories.map{|c| c.id}
    # add self, because sub categories has only the subs
    category_ids << self.id

    return Post.select{|p| p.categories.any? {|c| category_ids.include? c.id }}
    # return Post.select{|p| category_ids.include? p.category}
  end

  def to_param  # overridden
    slug
  end

  private

  def parent_not_self
    # check that the parent_category is not the same
    # select box should not show that in the first place
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :subscribe, :unsubscribe, :edit, :update]

  before_action :authenticate_user!, except: [:show, :index]

  def index
    if request.params[:search]
      @categories = Category.search(request.params[:search]).order(name: :asc).page(params[:page] ? params[:page] : 1)
    else
      @categories = Category.all.order(name: :asc).page(params[:page] ? params[:page] : 1)
    end
  end

  # def show
  #   # @categories = Category.all
  #   render :controller => 'posts_controller', :action => 'index'
  # end

  def new
    @category = Category.new
  end

  def edit
    authorize! :update, @category
  end

  def update
    authorize! :update, @category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user


    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def subscribe
    if !@category.subscribed(current_user) && @category.subscribe(current_user)
      redirect_to @category, notice: 'Successfully subscribed.'
    else
      redirect_to @category, notice: 'Could not subscribe.'
    end
  end

  def unsubscribe
    if @category.subscribed(current_user) && @category.unsubscribe(current_user)
      redirect_to @category, notice: 'Successfully unsubscribed.'
    else
      redirect_to @category, notice: 'Could not unsubscribe.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by_slug(params[:slug])
    end

    def category_params
      params.require(:category).permit(:name, :desc, :slug, :parent_category_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_header.html.erb
<h1><%= @category.name %> (
  <% if @category.subscribed(current_user) %>
      <%= link_to('Unsubscribe', unsubscribe_category_path(@category)) %>
  <% else %>
      <%= link_to('Subscribe', subscribe_category_path(@category)) %>
  <% end %>
  ) </h1>
<% if @category.parent_category %>
    <h5>Parent-Slackegory: <%= link_to @category.parent_category.name, @category.parent_category %></h5>
<% end %>
<% if not @category.sub_categories.empty? %>
    <h5>Sub-Slackegories:
      <% @category.sub_categories.each do |c| %>
          <%= link_to c.name, c %>
      <% end %>

    </h5>
<% end %>
<h3><%= @category.desc %></h3>

<% if can? :update, @category %>
<br>
    <%= link_to 'Edit Slackegory', edit_category_path(@category) %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for (@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label 'Description' %><br>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :slug %>&nbsp;<i class="gray-text">This is used for urls. You will be able to reach this slackegory through /slackegory/your_slug</i><br>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label 'Parent-Slackegory' %><br>
    <!-- Substract the category itself, to not allow select itself as parent -->
    <!-- Works aswell for new view and creating, as substracting something not in the array from it will not alter it -->
      <%= f.collection_select :parent_category_id, Category.order(:name) - [@category],:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/aashow.html.erb
<h1><%= @category.name %> (
    <% if @category.subscribed(current_user) %>
        <%= link_to('Unsubscribe', unsubscribe_category_path(@category)) %>
    <% else %>
        <%= link_to('Subscribe', subscribe_category_path(@category)) %>
    <% end %>
) </h1>
<% if @category.parent_category %>
    <h5>Überkategorie: <%= link_to @category.parent_category.name, @category.parent_category %></h5>
<% end %>
<% if not @category.sub_categories.empty? %>
    <h5>Unterkategorien: 
        <% @category.sub_categories.each do |c| %>
    <%= link_to c.name, c %> 
    <% end %>
        
    </h5>
<% end %>
<h3><%= @category.desc %></h3>

<% if can? :update, @category %>
    <%= link_to 'Kategorie bearbeiten', edit_category_path(@category) %>
<% end %>

<div class="posts">
    <%= render partial: "posts/post", collection: @posts %>
</div>
<br>

<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>

app/views/categories/edit.html.erb
<h2>Edit <%= @category.name %></h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>All Slackegories</h1>

<%= link_to 'Create new slackegory', new_category_path %>

<div class="search-container">
    <%= form_tag(categories_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search for slackegory" %>
        <%= submit_tag "Search", :name => nil %>
    <% end %>
</div>

<div class="pagination-container">
  <%= will_paginate @categories %>
</div>

<hr>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Parent Category</th>
            <th>Number of Posts</th>
        </tr>
    </thead>
    <tbody>
        <% @categories.each do |category| %>
            <tr>
                <td><%= link_to category.name, category %></td>
                <td><%= link_to category.parent_category.name, category.parent_category unless not category.parent_category %></td>
                <td><%= category.posts.size %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/categories/new.html.erb
<h2>Create new Slackegory</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %> (
    <% if @category.subscribed(current_user) %>
        <%= link_to('Unsubscribe', unsubscribe_category_path(@category)) %>
    <% else %>
        <%= link_to('Subscribe', subscribe_category_path(@category)) %>
    <% end %>
) </h1>
<% if @category.parent_category %>
    <h5>Überkategorie: <%= link_to @category.parent_category.name, @category.parent_category %></h5>
<% end %>
<% if not @category.sub_categories.empty? %>
    <h5>Unterkategorien: 
        <% @category.sub_categories.each do |c| %>
    <%= link_to c.name, c %> 
    <% end %>
        
    </h5>
<% end %>
<h3><%= @category.desc %></h3>

<% if can? :update, @category %>
    <%= link_to 'Kategorie bearbeiten', edit_category_path(@category) %>
<% end %>

<div class="posts">
    <%= render partial: "posts/post", collection: @posts %>
</div>
<br>

<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>