config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  constraints ValidSortOrder do

    devise_for :users
    resources :users do
      member do
        get 'posts(/:sortby)' => 'posts#user_posts', :as => :user_posts
        get 'favourites(/:sortby)' => 'posts#user_favourites', :as => :user_favourites
        get :admin_edit
        patch :admin_update
      end
    end

    resources :categories, :path => 'slackegory', param: :slug, :except => :show do
      member do
        get 'subscribe' => 'categories#subscribe'
        get 'unsubscribe' => 'categories#unsubscribe'
      end
    end
    get 'slackegory/:slug(/:sortby)' => 'posts#category', as: :category_posts



    get 'subscriptions/(:sortby)' => 'posts#subscriptions', :as => :subscriptions_posts
    
    resources :posts, :path => '/' do
      member do
        get 'upvote' => 'posts#upvote'
        get 'downvote' => 'posts#downvote'

        get 'favour' => 'posts#favour'
        get 'unfavour' => 'posts#unfavour'

        # DELETE is actually not very cruddy/resty for marking it as such, but makes it look like an actuall delete
        delete 'delete' => 'posts#mark_as_deleted'
      end
      collection do
        get '(:sortby)' => 'posts#index', :as => :sorted
      end
      resources :comments
    end
  end # ValidSortOrderConstraint

  authenticate :user, lambda { |u| u.admin? } do
    scope "/admin" do
      get 'posts/deleted' => 'posts#index_deleted', :as => :index_deleted
    end
  end






end

app/views/layouts/_application_header.html.erb
<header>
  <div class="header-container">
    <div class="page-header">
        <a href="<%= root_path %>" class="brand">SlackerNews 2.0</a> <small>alpha centauri</small>
    </div>
    <div class="header-search">
      <%= form_tag(sorted_posts_path(:sortby => params[:sortby]), :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search all posts" %>
        <%= submit_tag "Search", :name => nil %>
    <% end %>
    </div>
    <div class="menu-user">
        <% if user_signed_in? %>
          <%= link_to 'All Users', users_path %> | 
          <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>

            
          <div class="dropdown">
            <button class="dropbtn"><u>
              <%= current_user.name != "" ? current_user.name : 'this could be your name'%>
                
              </u></button>
            <div class="dropdown-content">
              <ul>
                  <li><%= link_to 'Show Profile', current_user %></li>
                  <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
                  <% if current_user.admin? %>
                    <li><%= link_to 'Deleted Posts', index_deleted_path %></li>
                  <% end %>
                  <%= render 'devise/menu/registration_items' %>
                  <%= render 'devise/menu/login_items' %>
              </ul>
            </div>
          </div>  
          <%= current_user.karma %>
        <% else %>
          <ul class="hmenu">
            <%= render 'devise/menu/login_items' %><%= render 'devise/menu/registration_items' %>
          </ul>
        <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">


  <title>
    <% if Rails.env.development? %>[DEV]<% end %>
    <%=[content_for(:title), 'SlackerNews'].compact.join(" :: ") %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
</head>
<body>

<div class="container">
	
<div class="row">
<div class="col-md-12">
  <%= render 'layouts/application_header' %>

	<hr class="clearfix">

	<%= yield %>
  <main>
        <% if notice %>
            <p id="notice" class="alert alert-info"><%= notice %></p>
        <% end %>
	</main>

	<hr>

	<footer>
    <div class="footer-column-left">
      <small>Powered by <a href="https://github.com/kaozente/SlackerNews">the mighty SlackerNews</a></small> | 
      <small>Do you have feature-requests, ideas or suggestions? Feel free to <a href="https://github.com/kaozente/SlackerNews/issues">file an issue!</a></small>
    </div>
    <div class="footer-column-right">
      <%= image_tag "works_on_my_machine.png", width: 50 %>
    </div>
  </footer>
</div>
</div>




</div>



</body>
</html>